version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: cv-backend
    ports:
      - '8000:80'
    volumes:
      - ./backend:/var/www/html
    networks:
      - cvnetwork

  frontend:
    build:
      context: ./frontend
    container_name: cv-frontend
    ports:
      - '3000:80'
    networks:
      - cvnetwork

networks:
  cvnetwork:
    driver: bridge
