services:
  - type: web
    name: cv-backend
    env: docker
    plan: free
    repo: https://github.com/AnatolyBystrov/cvproject
    branch: main
    dockerfilePath: backend/Dockerfile
    buildCommand: |
      cp .env .env.local || true
    startCommand: "./start.sh"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        value: base64:7A4AVnr0MYjeJeoo4cl6QK0TQ4HB66x/YjaCtBNFQvw=
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://cv-backend.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: database/database.sqlite
