apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-backend
  template:
    metadata:
      labels:
        app: cv-backend
    spec:
      containers:
        - name: cv-backend
          image: cvproject-backend
          imagePullPolicy: Never
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: cv-backend
spec:
  selector:
    app: cv-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
